### ISSUE TITLE
preparation_of_model_acacia_tortilis - missing points

### ISSUE THREAD

**Issue by KDolos** [KIT-IfGG/Malaria_SDM#1]
I do not have the data to check the code, right?

**Comment by JEFFGAFNA16** [comment]
Could you help me identify the reason why the presence points after preparing a model are greatly reduced. When I read the presence points at the beginning of the analysis and plot them on the map (ie of Africa) they appear many. But after preparing the model, these presence points greatly decline. I consulted Michael but we were unable to find a solution

**Comment by JEFFGAFNA16** [comment]
Yes. I got the solution after some time. I know where the problem was and it now works very well
